#!/bin/bash
INAME="${1##*/}"
VER="${INAME##* }"
NAME="${INAME##*-}"
NAME="${NAME% *}"
DIRC="temp/$NAME.app/Contents"
DIRA="temp/$NAME.app"
mkdir -p temp;
mkdir -p "$DIRC/Resources/icon.iconset"
mkdir "$DIRC/MacOS"
cp "$(which easyrpg-player)" "$DIRC/MacOS"
wrestool -xt 14 "$1/RPG_RT.exe" -o "$DIRC/Resources/icon.iconset/source.ico"
convert "$DIRC/Resources/icon.iconset/source.ico" -resize 16x16 "$DIRC/Resources/icon.iconset/icon_16x16.png"
convert "$DIRC/Resources/icon.iconset/source.ico" -resize 32x32 "$DIRC/Resources/icon.iconset/icon_16x16@2x.png"
convert "$DIRC/Resources/icon.iconset/source.ico" -resize 32x32 "$DIRC/Resources/icon.iconset/icon_32x32.png"
convert "$DIRC/Resources/icon.iconset/source.ico" -interpolate Nearest -filter point -resize 64x64 "$DIRC/Resources/icon.iconset/icon_32x32@2x.png"
convert "$DIRC/Resources/icon.iconset/source.ico" -interpolate Nearest -filter point -resize 128x128 "$DIRC/Resources/icon.iconset/icon_128x128.png"
convert "$DIRC/Resources/icon.iconset/source.ico" -interpolate Nearest -filter point -resize 256x256 "$DIRC/Resources/icon.iconset/icon_128x128@2x.png"
convert "$DIRC/Resources/icon.iconset/source.ico" -interpolate Nearest -filter point -resize 256x256 "$DIRC/Resources/icon.iconset/icon_256x256.png"
convert "$DIRC/Resources/icon.iconset/source.ico" -interpolate Nearest -filter point -resize 512x512 "$DIRC/Resources/icon.iconset/icon_256x256@2x.png"
convert "$DIRC/Resources/icon.iconset/source.ico" -interpolate Nearest -filter point -resize 512x512 "$DIRC/Resources/icon.iconset/icon_512x512.png"
convert "$DIRC/Resources/icon.iconset/source.ico" -interpolate Nearest -filter point -resize 1024x1024 "$DIRC/Resources/icon.iconset/icon_512x512@2x.png"
iconutil -c icns "$DIRC/Resources/icon.iconset"
rm -R "$DIRC/Resources/icon.iconset"
cp Info.plist "$DIRC"
sed -i '' s/"%%%TEMPLATEBUNDLENAME%%%"/"$NAME"/ "$DIRC/Info.plist"
sed -i '' s/"%%%TEMPLATEBUNDLEVERSION%%%"/"$VER"/ "$DIRC/Info.plist"
cp easyrpg-setup "$DIRC/MacOS/"
sed -i '' "s/%%%TEMPLATEBUNDLENAME%%%/$NAME/g" "$DIRC/MacOS/easyrpg-setup"
cp -R "$1" "$DIRC/MacOS/game"

hdiutil create -volname "$NAME" -srcfolder temp -format UDBZ "$INAME.dmg"
tar -C temp -czf "$INAME.tar.gz" "$NAME.app"
rm -R temp

echo "$INAME done"